const mongoose = require('mongoose');
require('dotenv').config();
const Member = require('../models/Member');
const Payment = require('../models/Payment');

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/oil-co-op';

async function seed() {
  try {
    await mongoose.connect(MONGODB_URI, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });
    
    console.log('Connected to MongoDB');
    
    // Clear existing data
    await Member.deleteMany({});
    await Payment.deleteMany({});
    console.log('Cleared existing data');
    
    // Create sample member (from screenshot)
    const member = new Member({
      status: 'ACTIVE',
      recType: '1',
      recTypeDropdown: 'IND',
      newMemberDate: new Date('2023-01-17'),
      senior: false,
      firstName1: 'Chris',
      lastName1: 'Marolda',
      firstName2: 'Annmarie',
      lastName2: 'Marolda',
      streetNo: '433',
      streetName: 'Tollgate Road',
      city: 'Berlin',
      state: 'CT',
      zip: '06037',
      phone1: '(860) 828-7559',
      phone1Type: 'HOME',
      phone2: '(860) 233-2181',
      phone2Type: 'WORK',
      phone2Ext: '309',
      email: 'chris@ccag.net',
      emailOptedOut: true,
      oilCoCode: 'PETRO',
      oilId: '6550778',
      propaneStatus: 'NO PROPANE',
      propCoCode: 'THOM',
      howJoined: 'PHO',
      referral: 'CCAG',
      deliveryPrograms: [
        { program: 'FLOAT', heatingYear: '2020' },
        { program: 'FLOAT', heatingYear: '2019' },
        { program: 'FLOAT', heatingYear: '2018' },
      ],
      electricStatus: 'UNKNOWN',
      elecSignUpDate: new Date('2020-11-14'),
      nameKey: 'MORA',
      droppedDate: new Date('2020-05-15'),
      electricityAccountNumber: '51299023036',
      theNextStep: 'Yes',
    });
    
    await member.save();
    console.log('Created sample member:', member._id);
    
    // Create payment record for this member
    const payment = new Payment({
      memberId: member._id,
      status: 'ACTIVE',
      propaneStatus: 'ACTIVE',
      senior: true,
      lifetimeMember: true,
      registrationFee: '10',
      dtPaid: new Date('2005-01-20'),
      checkCredit: '3698',
      registrationPaid: true,
      nameOnCreditCard: 'LEAD',
      renewalFees: [
        {
          billingYear: '2025',
          feeWaived: 'Yes',
          dateReceived: new Date('2025-06-01'),
          newRenew: 'Renew',
        },
        {
          billingYear: '2024',
          feeWaived: 'Yes',
          dateReceived: new Date('2024-06-01'),
          newRenew: 'Renew',
        },
        {
          billingYear: '2023',
          feeWaived: 'Yes',
          dateReceived: new Date('2023-06-01'),
          newRenew: 'Renew',
        },
      ],
      deliveryHistory: true,
    });
    
    await payment.save();
    console.log('Created payment record:', payment._id);
    
    // Create 20 diverse sample members
    const members = [
      {
        status: 'ACTIVE',
        recType: '1',
        recTypeDropdown: 'IND',
        newMemberDate: new Date('2020-03-15'),
        senior: true,
        firstName1: 'Robert',
        lastName1: 'Johnson',
        firstName2: 'Mary',
        lastName2: 'Johnson',
        streetNo: '127',
        streetName: 'Maple Drive',
        city: 'Hartford',
        state: 'CT',
        zip: '06103',
        phone1: '(860) 555-2101',
        phone1Type: 'HOME',
        phone2: '(860) 555-2102',
        phone2Type: 'CELL',
        email: 'rjohnson@email.com',
        oilCoCode: 'PETRO',
        oilId: '2101001',
        propaneStatus: 'ACTIVE',
        propCoCode: 'THOM',
        propaneId: 'PROP2101',
        howJoined: 'PHO',
        referral: 'FRIEND',
        senior: true,
      },
      {
        status: 'ACTIVE',
        firstName1: 'Patricia',
        lastName1: 'Williams',
        streetNo: '89',
        streetName: 'Elm Street',
        aptNo: '2B',
        city: 'New Haven',
        state: 'CT',
        zip: '06511',
        phone1: '(203) 555-3201',
        phone1Type: 'HOME',
        email: 'pwilliams@gmail.com',
        oilCoCode: 'THOM',
        oilId: '3201001',
        propaneStatus: 'NO PROPANE',
        howJoined: 'REF',
        referral: 'NEIGHBOR',
        newMemberDate: new Date('2021-06-20'),
      },
      {
        status: 'PROSPECTIVE',
        firstName1: 'Michael',
        lastName1: 'Brown',
        firstName2: 'Sarah',
        lastName2: 'Brown',
        streetNo: '245',
        streetName: 'Oak Avenue',
        city: 'Stamford',
        state: 'CT',
        zip: '06901',
        phone1: '(203) 555-4301',
        phone1Type: 'CELL',
        phone2: '(203) 555-4302',
        phone2Type: 'WORK',
        phone2Ext: '101',
        email: 'mbrown@company.com',
        oilCoCode: 'PETRO',
        howJoined: 'PHO',
        newMemberDate: new Date('2024-01-10'),
      },
      {
        status: 'ACTIVE',
        firstName1: 'Jennifer',
        lastName1: 'Davis',
        streetNo: '512',
        streetName: 'Park Road',
        city: 'Bridgeport',
        state: 'CT',
        zip: '06604',
        phone1: '(203) 555-5401',
        phone1Type: 'HOME',
        email: 'jdavis@email.com',
        oilCoCode: 'THOM',
        oilId: '5401001',
        propaneStatus: 'ACTIVE',
        propCoCode: 'PETRO',
        propaneId: 'PROP5401',
        howJoined: 'REF',
        referral: 'FAMILY',
        senior: true,
        newMemberDate: new Date('2019-11-05'),
      },
      {
        status: 'RESIDENT',
        firstName1: 'David',
        lastName1: 'Miller',
        firstName2: 'Lisa',
        lastName2: 'Miller',
        streetNo: '678',
        streetName: 'Cedar Lane',
        city: 'Waterbury',
        state: 'CT',
        zip: '06702',
        phone1: '(203) 555-6501',
        phone1Type: 'HOME',
        phone2: '(203) 555-6502',
        phone2Type: 'CELL',
        email: 'dmiller@email.com',
        oilCoCode: 'PETRO',
        oilId: '6501001',
        propaneStatus: 'NO PROPANE',
        howJoined: 'PHO',
        newMemberDate: new Date('2022-08-15'),
      },
      {
        status: 'ACTIVE',
        firstName1: 'Linda',
        lastName1: 'Wilson',
        streetNo: '334',
        streetName: 'Birch Street',
        city: 'Norwalk',
        state: 'CT',
        zip: '06850',
        phone1: '(203) 555-7601',
        phone1Type: 'CELL',
        email: 'lwilson@email.com',
        oilCoCode: 'THOM',
        oilId: '7601001',
        propaneStatus: 'ACTIVE',
        propCoCode: 'THOM',
        propaneId: 'PROP7601',
        howJoined: 'REF',
        referral: 'FRIEND',
        senior: true,
        newMemberDate: new Date('2018-04-22'),
      },
      {
        status: 'INACTIVE',
        firstName1: 'James',
        lastName1: 'Moore',
        streetNo: '156',
        streetName: 'Pine Street',
        city: 'Danbury',
        state: 'CT',
        zip: '06810',
        phone1: '(203) 555-8701',
        phone1Type: 'HOME',
        email: 'jmoore@email.com',
        oilCoCode: 'PETRO',
        oilId: '8701001',
        propaneStatus: 'INACTIVE',
        howJoined: 'PHO',
        newMemberDate: new Date('2020-09-30'),
      },
      {
        status: 'ACTIVE',
        firstName1: 'Barbara',
        lastName1: 'Taylor',
        firstName2: 'Thomas',
        lastName2: 'Taylor',
        streetNo: '789',
        streetName: 'Spruce Avenue',
        city: 'New Britain',
        state: 'CT',
        zip: '06051',
        phone1: '(860) 555-9801',
        phone1Type: 'HOME',
        phone2: '(860) 555-9802',
        phone2Type: 'WORK',
        email: 'btaylor@email.com',
        oilCoCode: 'THOM',
        oilId: '9801001',
        propaneStatus: 'NO PROPANE',
        howJoined: 'REF',
        referral: 'NEIGHBOR',
        newMemberDate: new Date('2021-02-14'),
      },
      {
        status: 'PROSPECTIVE',
        firstName1: 'Richard',
        lastName1: 'Anderson',
        streetNo: '423',
        streetName: 'Willow Way',
        city: 'West Hartford',
        state: 'CT',
        zip: '06107',
        phone1: '(860) 555-0901',
        phone1Type: 'CELL',
        email: 'randerson@email.com',
        oilCoCode: 'PETRO',
        howJoined: 'PHO',
        newMemberDate: new Date('2024-02-01'),
      },
      {
        status: 'ACTIVE',
        firstName1: 'Susan',
        lastName1: 'Thomas',
        streetNo: '567',
        streetName: 'Ash Street',
        city: 'Greenwich',
        state: 'CT',
        zip: '06830',
        phone1: '(203) 555-1011',
        phone1Type: 'HOME',
        phone2: '(203) 555-1012',
        phone2Type: 'CELL',
        email: 'sthomas@email.com',
        oilCoCode: 'THOM',
        oilId: '1011001',
        propaneStatus: 'ACTIVE',
        propCoCode: 'PETRO',
        propaneId: 'PROP1011',
        howJoined: 'REF',
        referral: 'FAMILY',
        senior: true,
        newMemberDate: new Date('2017-07-18'),
      },
      {
        status: 'ACTIVE',
        firstName1: 'Joseph',
        lastName1: 'Jackson',
        firstName2: 'Karen',
        lastName2: 'Jackson',
        streetNo: '234',
        streetName: 'Hickory Drive',
        city: 'Hamden',
        state: 'CT',
        zip: '06514',
        phone1: '(203) 555-1121',
        phone1Type: 'HOME',
        email: 'jjackson@email.com',
        oilCoCode: 'PETRO',
        oilId: '1121001',
        propaneStatus: 'NO PROPANE',
        howJoined: 'PHO',
        newMemberDate: new Date('2022-05-10'),
      },
      {
        status: 'RESIDENT',
        firstName1: 'Jessica',
        lastName1: 'White',
        streetNo: '891',
        streetName: 'Cherry Lane',
        city: 'Meriden',
        state: 'CT',
        zip: '06450',
        phone1: '(203) 555-1231',
        phone1Type: 'CELL',
        email: 'jwhite@email.com',
        oilCoCode: 'THOM',
        oilId: '1231001',
        propaneStatus: 'ACTIVE',
        propCoCode: 'THOM',
        propaneId: 'PROP1231',
        howJoined: 'REF',
        referral: 'FRIEND',
        newMemberDate: new Date('2023-03-25'),
      },
      {
        status: 'ACTIVE',
        firstName1: 'Charles',
        lastName1: 'Harris',
        firstName2: 'Nancy',
        lastName2: 'Harris',
        streetNo: '456',
        streetName: 'Poplar Street',
        city: 'Bristol',
        state: 'CT',
        zip: '06010',
        phone1: '(860) 555-1341',
        phone1Type: 'HOME',
        phone2: '(860) 555-1342',
        phone2Type: 'WORK',
        phone2Ext: '205',
        email: 'charris@email.com',
        oilCoCode: 'PETRO',
        oilId: '1341001',
        propaneStatus: 'NO PROPANE',
        howJoined: 'PHO',
        senior: true,
        newMemberDate: new Date('2019-12-08'),
      },
      {
        status: 'PROSPECTIVE',
        firstName1: 'Sarah',
        lastName1: 'Martin',
        streetNo: '678',
        streetName: 'Sycamore Avenue',
        city: 'Middletown',
        state: 'CT',
        zip: '06457',
        phone1: '(860) 555-1451',
        phone1Type: 'CELL',
        email: 'smartin@email.com',
        oilCoCode: 'THOM',
        howJoined: 'REF',
        referral: 'NEIGHBOR',
        newMemberDate: new Date('2024-01-20'),
      },
      {
        status: 'ACTIVE',
        firstName1: 'Daniel',
        lastName1: 'Thompson',
        streetNo: '123',
        streetName: 'Beech Road',
        city: 'Manchester',
        state: 'CT',
        zip: '06040',
        phone1: '(860) 555-1561',
        phone1Type: 'HOME',
        email: 'dthompson@email.com',
        oilCoCode: 'PETRO',
        oilId: '1561001',
        propaneStatus: 'ACTIVE',
        propCoCode: 'PETRO',
        propaneId: 'PROP1561',
        howJoined: 'REF',
        referral: 'FAMILY',
        newMemberDate: new Date('2021-09-12'),
      },
      {
        status: 'ACTIVE',
        firstName1: 'Amy',
        lastName1: 'Garcia',
        firstName2: 'Mark',
        lastName2: 'Garcia',
        streetNo: '789',
        streetName: 'Chestnut Street',
        city: 'West Haven',
        state: 'CT',
        zip: '06516',
        phone1: '(203) 555-1671',
        phone1Type: 'HOME',
        phone2: '(203) 555-1672',
        phone2Type: 'CELL',
        email: 'agarcia@email.com',
        oilCoCode: 'THOM',
        oilId: '1671001',
        propaneStatus: 'NO PROPANE',
        howJoined: 'PHO',
        newMemberDate: new Date('2022-11-03'),
      },
      {
        status: 'INACTIVE',
        firstName1: 'Paul',
        lastName1: 'Martinez',
        streetNo: '345',
        streetName: 'Walnut Drive',
        city: 'Milford',
        state: 'CT',
        zip: '06460',
        phone1: '(203) 555-1781',
        phone1Type: 'CELL',
        email: 'pmartinez@email.com',
        oilCoCode: 'PETRO',
        oilId: '1781001',
        propaneStatus: 'INACTIVE',
        howJoined: 'REF',
        referral: 'FRIEND',
        newMemberDate: new Date('2020-10-15'),
      },
      {
        status: 'ACTIVE',
        firstName1: 'Michelle',
        lastName1: 'Robinson',
        streetNo: '567',
        streetName: 'Magnolia Lane',
        city: 'Torrington',
        state: 'CT',
        zip: '06790',
        phone1: '(860) 555-1891',
        phone1Type: 'HOME',
        email: 'mrobinson@email.com',
        oilCoCode: 'THOM',
        oilId: '1891001',
        propaneStatus: 'ACTIVE',
        propCoCode: 'THOM',
        propaneId: 'PROP1891',
        howJoined: 'PHO',
        senior: true,
        newMemberDate: new Date('2018-06-20'),
      },
      {
        status: 'PROSPECTIVE',
        firstName1: 'Kevin',
        lastName1: 'Clark',
        firstName2: 'Emily',
        lastName2: 'Clark',
        streetNo: '234',
        streetName: 'Dogwood Avenue',
        city: 'Enfield',
        state: 'CT',
        zip: '06082',
        phone1: '(860) 555-1901',
        phone1Type: 'CELL',
        email: 'kclark@email.com',
        oilCoCode: 'PETRO',
        howJoined: 'REF',
        referral: 'NEIGHBOR',
        newMemberDate: new Date('2024-02-15'),
      },
      {
        status: 'ACTIVE',
        firstName1: 'Laura',
        lastName1: 'Rodriguez',
        streetNo: '890',
        streetName: 'Redwood Street',
        city: 'Stratford',
        state: 'CT',
        zip: '06614',
        phone1: '(203) 555-2011',
        phone1Type: 'HOME',
        phone2: '(203) 555-2012',
        phone2Type: 'WORK',
        email: 'lrodriguez@email.com',
        oilCoCode: 'THOM',
        oilId: '2011001',
        propaneStatus: 'NO PROPANE',
        howJoined: 'PHO',
        newMemberDate: new Date('2023-07-08'),
      },
    ];
    
    // Create members and their payment records
    for (const memberData of members) {
      const newMember = new Member(memberData);
      await newMember.save();
      console.log(`Created member: ${newMember.firstName1} ${newMember.lastName1} (${newMember._id})`);
      
      // Create payment record for active/resident members
      if (memberData.status === 'ACTIVE' || memberData.status === 'RESIDENT') {
        const payment = new Payment({
          memberId: newMember._id,
          status: newMember.status,
          propaneStatus: newMember.propaneStatus || 'NO PROPANE',
          senior: newMember.senior || false,
          lifetimeMember: Math.random() > 0.7, // 30% chance
          registrationFee: '10',
          dtPaid: new Date(newMember.newMemberDate.getTime() - Math.random() * 365 * 24 * 60 * 60 * 1000),
          checkCredit: String(Math.floor(Math.random() * 9000) + 1000),
          registrationPaid: true,
          renewalFees: [
            {
              billingYear: '2025',
              feeWaived: Math.random() > 0.5 ? 'Yes' : 'No',
              dateReceived: new Date('2025-06-01'),
              amountReceived: '',
              paymentMethod: '',
              newRenew: 'Renew',
            },
            {
              billingYear: '2024',
              feeWaived: Math.random() > 0.5 ? 'Yes' : 'No',
              dateReceived: new Date('2024-06-01'),
              amountReceived: '',
              paymentMethod: '',
              newRenew: 'Renew',
            },
            {
              billingYear: '2023',
              feeWaived: Math.random() > 0.5 ? 'Yes' : 'No',
              dateReceived: new Date('2023-06-01'),
              amountReceived: '',
              paymentMethod: '',
              newRenew: 'Renew',
            },
          ],
          deliveryHistory: true,
        });
        await payment.save();
      }
    }
    
    console.log('\n✅ Database seeded successfully!');
    console.log(`Created ${await Member.countDocuments()} members`);
    console.log(`Created ${await Payment.countDocuments()} payment records`);
    
    process.exit(0);
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
}

seed();
